import { Router } from "express";
import { z } from "zod";
import { Prisma } from "@prisma/client";
import { prisma } from "../db";
import { asyncHandler, HttpError } from "../middleware/errorHandler";
import { dateOnlyKey, startOfDay, startOfMonth, startOfNextDay, startOfNextMonth } from "../utils/dates";
import { expenseGroups, noteSuggestions, normaliseNote, SPOILAGE_EXPENSE_PREFIX } from "../utils/expenseBreakdown";
import { applyCashDeduction } from "./cashRegister.routes";

export const expensesRouter = Router();

// The till entry an expense creates, readable on its own in the cash ledger:
// "Expense: Other - electricity" rather than just "Expense: Other", which
// says nothing about where the money went.
function ledgerNote(name: string, notes: string | null | undefined): string {
  const note = normaliseNote(notes);
  return note ? `Expense: ${name} - ${note}` : `Expense: ${name}`;
}

const expenseInput = z.object({
  name: z.string().trim().min(1),
  amount: z.number().positive(),
  category: z.string().trim().optional().nullable(),
  date: z.coerce.date().optional(),
  notes: z.string().trim().optional().nullable(),
});

expensesRouter.get(
  "/",
  asyncHandler(async (_req, res) => {
    const expenses = await prisma.expense.findMany({ orderBy: { date: "desc" } });
    res.json(expenses);
  })
);

// An expense's name *is* its category ("Rent", "Cashier salary", ...) -
// there's no separate category concept, since in practice every expense
// worth grouping is another instance of one that was logged before. This
// returns the distinct names already in use so the app can offer them as
// a dropdown and as quick-add chips instead of the owner retyping (and
// misspelling, which would split one grouping into two). Typing a new
// name creates that grouping implicitly.
expensesRouter.get(
  "/names",
  asyncHandler(async (_req, res) => {
    const rows = await prisma.expense.findMany({
      // Spoilage write-offs are generated by the spoilage flow, not typed
      // by anyone, so they don't belong among the names offered for logging
      // a new expense - nobody adds "Spoiled: Corn" by hand. They stay in
      // the expense list and in the totals; they're only excluded as a
      // suggestion. The name check covers write-offs recorded before the
      // link column existed.
      where: {
        inventoryTransactionId: null,
        NOT: { name: { startsWith: SPOILAGE_EXPENSE_PREFIX } },
      },
      distinct: ["name"],
      select: { name: true },
      orderBy: { name: "asc" },
    });
    res.json(rows.map((r) => r.name).filter((n) => n !== ""));
  })
);

// Notes already written under one expense name, most used first - offered
// by the app as one-tap suggestions while logging another, so "electricity"
// is picked rather than retyped as "Electricity " or "electrcity" and the
// report's breakdown keeps it on one line.
expensesRouter.get(
  "/notes",
  asyncHandler(async (req, res) => {
    const name = typeof req.query.name === "string" ? req.query.name.trim() : "";
    if (!name) {
      res.json([]);
      return;
    }
    const rows = await prisma.expense.findMany({
      where: { name, notes: { not: null } },
      select: { notes: true, date: true },
    });
    res.json(noteSuggestions(rows));
  })
);

// GET /api/expenses/for-range?period=day|month&date= - the expense side of
// profit for a specific calendar day or month, mirroring the dashboard
// summary's math for an arbitrary period instead of just "today"/"this
// month". Also surfaces the deficit (amount that couldn't be paid from the
// cash register) accumulated over that same period.
expensesRouter.get(
  "/for-range",
  asyncHandler(async (req, res) => {
    const period = req.query.period === "month" ? "month" : "day";
    const dateParam = typeof req.query.date === "string" ? new Date(req.query.date) : new Date();
    const from = period === "month" ? startOfMonth(dateParam) : startOfDay(dateParam);
    const to = period === "month" ? startOfNextMonth(dateParam) : startOfNextDay(dateParam);

    const items = await prisma.expense.findMany({
      where: { date: { gte: from, lt: to } },
      orderBy: { date: "desc" },
    });
    const total = items.reduce((acc, e) => acc.add(e.amount), new Prisma.Decimal(0));
    const deficit = items.reduce((acc, e) => acc.add(e.deficitAmount), new Prisma.Decimal(0));

    res.json({
      period,
      date: dateOnlyKey(dateParam).toISOString().slice(0, 10),
      items,
      total,
      deficit,
      // Grouped by name - see the /names endpoint above for why the name
      // is the category for an expense - each with its breakdown by note,
      // and spoilage write-offs folded into one group broken down by product.
      // See expenseGroups.
      byCategory: await expenseGroups(prisma, items),
    });
  })
);

expensesRouter.post(
  "/",
  asyncHandler(async (req, res) => {
    const data = expenseInput.parse(req.body);
    const expense = await prisma.$transaction(async (tx) => {
      const created = await tx.expense.create({ data: { ...data, notes: normaliseNote(data.notes) } });
      await applyCashDeduction(tx, { expenseId: created.id }, created.amount, ledgerNote(created.name, created.notes));
      return created;
    });
    res.status(201).json(expense);
  })
);

expensesRouter.put(
  "/:id",
  asyncHandler(async (req, res) => {
    const data = expenseInput.partial().parse(req.body);
    const expense = await prisma.$transaction(async (tx) => {
      const existing = await tx.expense.findUnique({ where: { id: req.params.id } });
      if (!existing) throw new HttpError(404, "Expense not found");
      const updated = await tx.expense.update({
        where: { id: req.params.id },
        data: data.notes === undefined ? data : { ...data, notes: normaliseNote(data.notes) },
      });
      await applyCashDeduction(tx, { expenseId: updated.id }, updated.amount, ledgerNote(updated.name, updated.notes));
      // Reached only if applyCashDeduction succeeded (fully paid), so any
      // deficit this expense carried from before this edit no longer
      // applies - clear it rather than leaving a stale value behind.
      if (updated.deficitAmount.gt(0)) {
        return tx.expense.update({ where: { id: updated.id }, data: { deficitAmount: 0 } });
      }
      return updated;
    });
    res.json(expense);
  })
);

expensesRouter.delete(
  "/:id",
  asyncHandler(async (req, res) => {
    await prisma.$transaction(async (tx) => {
      const existing = await tx.expense.findUnique({ where: { id: req.params.id } });
      if (!existing) throw new HttpError(404, "Expense not found");
      await tx.cashRegisterEntry.deleteMany({ where: { expenseId: existing.id } });
      await tx.expense.delete({ where: { id: req.params.id } });
    });
    res.status(204).send();
  })
);
